package com.example.day9application;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.administrator.shoppingproject.Base.GreenDao;
import com.example.administrator.shoppingproject.Base.PhoneGreen;

import com.example.day9application.GreenDaoDao;
import com.example.day9application.PhoneGreenDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig greenDaoDaoConfig;
    private final DaoConfig phoneGreenDaoConfig;

    private final GreenDaoDao greenDaoDao;
    private final PhoneGreenDao phoneGreenDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        greenDaoDaoConfig = daoConfigMap.get(GreenDaoDao.class).clone();
        greenDaoDaoConfig.initIdentityScope(type);

        phoneGreenDaoConfig = daoConfigMap.get(PhoneGreenDao.class).clone();
        phoneGreenDaoConfig.initIdentityScope(type);

        greenDaoDao = new GreenDaoDao(greenDaoDaoConfig, this);
        phoneGreenDao = new PhoneGreenDao(phoneGreenDaoConfig, this);

        registerDao(GreenDao.class, greenDaoDao);
        registerDao(PhoneGreen.class, phoneGreenDao);
    }
    
    public void clear() {
        greenDaoDaoConfig.clearIdentityScope();
        phoneGreenDaoConfig.clearIdentityScope();
    }

    public GreenDaoDao getGreenDaoDao() {
        return greenDaoDao;
    }

    public PhoneGreenDao getPhoneGreenDao() {
        return phoneGreenDao;
    }

}
