package com.example.day9application;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.administrator.shoppingproject.Base.GreenDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GREEN_DAO".
*/
public class GreenDaoDao extends AbstractDao<GreenDao, String> {

    public static final String TABLENAME = "GREEN_DAO";

    /**
     * Properties of entity GreenDao.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Tittle = new Property(0, String.class, "Tittle", true, "TITTLE");
        public final static Property Text = new Property(1, String.class, "Text", false, "TEXT");
    }


    public GreenDaoDao(DaoConfig config) {
        super(config);
    }
    
    public GreenDaoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GREEN_DAO\" (" + //
                "\"TITTLE\" TEXT PRIMARY KEY NOT NULL ," + // 0: Tittle
                "\"TEXT\" TEXT);"); // 1: Text
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GREEN_DAO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, GreenDao entity) {
        stmt.clearBindings();
 
        String Tittle = entity.getTittle();
        if (Tittle != null) {
            stmt.bindString(1, Tittle);
        }
 
        String Text = entity.getText();
        if (Text != null) {
            stmt.bindString(2, Text);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, GreenDao entity) {
        stmt.clearBindings();
 
        String Tittle = entity.getTittle();
        if (Tittle != null) {
            stmt.bindString(1, Tittle);
        }
 
        String Text = entity.getText();
        if (Text != null) {
            stmt.bindString(2, Text);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public GreenDao readEntity(Cursor cursor, int offset) {
        GreenDao entity = new GreenDao( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // Tittle
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // Text
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, GreenDao entity, int offset) {
        entity.setTittle(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setText(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final String updateKeyAfterInsert(GreenDao entity, long rowId) {
        return entity.getTittle();
    }
    
    @Override
    public String getKey(GreenDao entity) {
        if(entity != null) {
            return entity.getTittle();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(GreenDao entity) {
        return entity.getTittle() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
