package com.example.day9application;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.administrator.shoppingproject.Base.PhoneGreen;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PHONE_GREEN".
*/
public class PhoneGreenDao extends AbstractDao<PhoneGreen, String> {

    public static final String TABLENAME = "PHONE_GREEN";

    /**
     * Properties of entity PhoneGreen.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Phonenumber = new Property(0, String.class, "phonenumber", true, "PHONENUMBER");
        public final static Property Password = new Property(1, String.class, "password", false, "PASSWORD");
    }


    public PhoneGreenDao(DaoConfig config) {
        super(config);
    }
    
    public PhoneGreenDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PHONE_GREEN\" (" + //
                "\"PHONENUMBER\" TEXT PRIMARY KEY NOT NULL ," + // 0: phonenumber
                "\"PASSWORD\" TEXT);"); // 1: password
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PHONE_GREEN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, PhoneGreen entity) {
        stmt.clearBindings();
 
        String phonenumber = entity.getPhonenumber();
        if (phonenumber != null) {
            stmt.bindString(1, phonenumber);
        }
 
        String password = entity.getPassword();
        if (password != null) {
            stmt.bindString(2, password);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, PhoneGreen entity) {
        stmt.clearBindings();
 
        String phonenumber = entity.getPhonenumber();
        if (phonenumber != null) {
            stmt.bindString(1, phonenumber);
        }
 
        String password = entity.getPassword();
        if (password != null) {
            stmt.bindString(2, password);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public PhoneGreen readEntity(Cursor cursor, int offset) {
        PhoneGreen entity = new PhoneGreen( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // phonenumber
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // password
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, PhoneGreen entity, int offset) {
        entity.setPhonenumber(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setPassword(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final String updateKeyAfterInsert(PhoneGreen entity, long rowId) {
        return entity.getPhonenumber();
    }
    
    @Override
    public String getKey(PhoneGreen entity) {
        if(entity != null) {
            return entity.getPhonenumber();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(PhoneGreen entity) {
        return entity.getPhonenumber() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
